const content = [
  {
    index: '1',
    name: 'ŠAMPUK CITRONOVÁ TRÁVA, TEA TREE',
    ingredients:
      'složení - sodium coco sulfát, babassu olej, ricinový olej, bambucké máslo, konopný protein, heřmánkový výluh, esenciální oleje, vitamín E',
    description:
      'hydratuje, regeneruje, zrychluje růst vlasů, omezuje svědění pokožky',
    details: 'praktická velikost, krabička a použití',
    price: 105,
    amount: '25 g',
    category: 'kosmetika',
    subcategory: 'Vlasy',
    image: '../../img/sampuk.jpg',
    null: null,
  },
  {
    index: '2',
    name: 'TUHÝ DEODORANT CITRONOVÁ TRÁVA, TEA TREE',
    ingredients:
      'složení - kokosový olej, včelí vosk, kakaové máslo, jedlá soda, kukuřičný škrob, esenciální oleje',
    description:
      'krásně vonící deodorant čistě z přírodních surovin, o dezodorační vlastnosti se postará kokosový olej, jedlá soda a tea tree',
    details: 'praktická velikost v tubě, neroztéká se ani v horku',
    price: 80,
    amount: '15 ml',
    category: 'kosmetika',
    subcategory: 'Tělo',
    image: '../../img/deodorant.jpg',
    null: null,
  },
  {
    index: '3',
    name: 'BALZÁM NA RTY POMERANČ, MÁTA',
    ingredients:
      'složení - bambucké máslo, kakaové máslo, včelí vosk, esenciální oleje, vitamín E',
    description: 'jednoduchý hydratační balzám v krabičce se svěží vůní',
    details: null,
    price: 45,
    amount: '10 ml',
    category: 'kosmetika',
    subcategory: 'Obličej a rty',
    image: '../../img/balzam.jpg',
    null: null,
  },
  {
    index: '4',
    name: 'LESK NA RTY MALINOVÝ',
    ingredients:
      'složení - bambucké máslo, kakaové máslo, včelí vosk, esenciální oleje, vitamín E, růžová mica',
    description: 'krásně malinami vonící balzám na rty s růžovým leskem',
    details: null,
    price: 50,
    amount: '10 ml',
    category: 'kosmetika',
    subcategory: 'Obličej a rty',
    image: '../../img/lesk.jpg',
    null: null,
  },
  {
    index: '5',
    name: 'TUHÝ PARFÉMEK KVĚTINOVÝ',
    ingredients: 'složení - jojobový olej, včelí vosk, esenciální oleje',
    description: 'mini parfém do kabelky s krásnou květinovou vůní',
    details: null,
    price: 50,
    amount: '10 ml',
    category: 'kosmetika',
    subcategory: 'Vůně',
    image: '../../img/parfem.jpg',
    null: null,
  },
  {
    index: '6',
    name: 'MĚSÍČKOVÁ MAST',
    ingredients: 'složení - měsíčkový olej, kakaové máslo, včelí vosk',
    description:
      'obsahuje domácí extrakt z měsíčku pro co nejsilnější účinky - zejména na kožní problémy, křečové žíly, popáleniny, ekzémy, opruzeniny atd.',
    details: 'oblíbený také při péči o děti',
    price: 165,
    amount: '50 ml',
    category: 'kosmetika',
    subcategory: 'Funkční masti',
    image: '../../img/mesickova-mast.jpg',
    null: null,
  },
  {
    index: '7',
    name: 'TYMIÁNOVÁ MAST PROTI RÝMĚ',
    ingredients:
      'složení - bambucké máslo, kokosový olej, olivový olej, tymián, esenciální olej',
    description:
      'čistě přírodní metoda, můžou používat i děti, stačí namazat pod nos, příp. na hruď atd.',
    details: null,
    price: 80,
    amount: '50 ml',
    category: 'kosmetika',
    subcategory: 'Funkční masti',
    image: '../../img/tymianova-mast.jpg',
    null: null,
  },
  {
    index: '8',
    name: 'NOČNÍ MÁSLO NA BOLAVÉ NOHY',
    ingredients:
      'složení - bambucké máslo, kokosový olej, kakaové máslo, esenciální oleje (citronová tráva, tea tree)',
    description:
      'výživa pro nohy, která jim přes noc uleví a krásně vyživí. Namazat, nasadit tlusté ponožky, jít si lehnout a víc se o to nestarat :)',
    details: null,
    price: 85,
    amount: '100 g',
    category: 'kosmetika',
    subcategory: 'Tělo',
    image: '../../img/nocni-maslo.jpg',
    null: null,
  },
  {
    index: '9',
    name: 'BOMBA DO KOUPELE',
    ingredients:
      'složení - jedlá soda, kyselina citronová, himalajská sůl, esenciální oleje, bylinky, barvivo',
    description:
      'klasická šumivá bomba do koupele, jen bez chemických přísad. Přísady a esence na přání nebo náhodně dle aktuálních zásob',
    details: null,
    price: 45,
    amount: '100 g',
    category: 'kosmetika',
    subcategory: 'Koupel',
    image: '../../img/bomba.jpg',
    null: null,
  },
  {
    index: '10',
    name: 'VOŇAVÁ DĚTSKÁ BOMBA S PŘEKVAPENÍM',
    ingredients:
      'složení - jedlá soda, kyselina citronová, himalajská sůl, esenciální oleje, barvivo',
    description:
      'během koupání se děti pobaví s krásně voňavou a šumivou bombou a navíc uvnitř najdou překvapení v podobě malé hračky',
    details: null,
    price: 45,
    amount: '80 g',
    category: 'kosmetika',
    subcategory: 'Koupel',
    image: '../../img/detska-bomba.jpg',
    null: null,
  },
  {
    index: '11',
    name: 'KOUPELOVÉ PRALINKY S VŮNÍ ČOKOLÁDY',
    ingredients:
      'složení - jedlá soda, kyselina citronová, sušené mléko, kakaové máslo, bambucké máslo, mandlový olej, esenciální oleje',
    description:
      'luxusní alternativa šumivých bomb, extrémně pěstící díky použitým tukům. Vhodné také jako vtipný dárek',
    details: null,
    price: 130,
    amount: '15 ks',
    category: 'kosmetika',
    subcategory: 'Koupel',
    image: '../../img/pralinky.jpg',
    null: null,
  },
  {
    index: '12',
    name: 'ZUBNÍ PASTA S MÁTOU A TEA TREE',
    ingredients:
      'složení - kokosový olej, jedlá soda, xylitol, esenciální oleje',
    description:
      'funkční a zdravá zubní pasta s příjemnou vůní máty. Pro delší trvanlivost nabírejte na kartáček přiloženou špachtlí',
    details: null,
    price: 80,
    amount: '50 ml',
    category: 'kosmetika',
    subcategory: 'Zuby',
    image: '../../img/zubni-pasta.jpg',
    null: null,
  },
  {
    index: '13',
    name: 'PRACÍ PRÁŠEK',
    ingredients:
      'složení - marseillské mýdlo, prací soda, perkarbonát sodný, taed',
    description:
      'funkční prášek s příjemnou jemnou vůní, vhodný i pro citlivou pokožku dětí. Dodáváno ve dvou nádobách (směs v druhé nádobě se přidává do bílého prádla)',
    details: null,
    price: 250,
    amount: '1,5 kg',
    category: 'drogerie',
    subcategory: 'Praní',
    image: '../../img/praci-prasek.jpg',
    null: null,
  },
  {
    index: '14',
    name: 'PRACÍ GEL',
    ingredients:
      'složení - marseillské mýdlo, prací soda, perkarbonát sodný, taed',
    description:
      'funkční prací gel s příjemnou jemnou vůní, vhodný i pro citlivou pokožku dětí. Dodáváno ve dvou nádobách (směs v druhé nádobě se přidává do bílého prádla)',
    details: null,
    price: 150,
    amount: '2 l',
    category: 'drogerie',
    subcategory: 'Praní',
    image: '../../img/praci-gel.jpg',
    null: null,
  },
  {
    index: '15',
    name: 'TABLETY DO MYČKY',
    ingredients:
      'složení - jedlá soda, prací soda, himalajská sůl, kyselina citronová',
    description:
      'jednoduché složení, malá cena a stejná efektivita. Jako leštidlo je dobré použít bílý vinný ocet při každém mytí.',
    details: null,
    price: 60,
    amount: '30 ks',
    category: 'drogerie',
    subcategory: 'Úklid',
    image: '../../img/tablety.jpg',
    null: null,
  },
  {
    index: '16',
    name: 'ŠUMIVKY DO WC',
    ingredients: 'složení - jedlá soda, kyselina citronová, esenciální oleje',
    description:
      'roztomilé kytičky, které se občas hodí do záchodu, a spolehlivě vydezinfikují a vyvoní toaletu',
    details: null,
    price: 50,
    amount: '30 ks',
    category: 'drogerie',
    subcategory: 'Úklid',
    image: '../../img/sumivky.jpg',
    null: null,
  },
  {
    index: '17',
    name: 'SADA BOMB DO KOUPELE',
    ingredients: null,
    description: 'různé druhy bomb',
    details: null,
    price: 310,
    amount: '6 ks',
    category: 'darkove-sady',
    subcategory: null,
    image: '../../img/sada-bomb.jpg',
    null: null,
  },
  {
    index: '18',
    name: 'SADA KOUPELOVÝCH PRALINEK',
    ingredients: null,
    description: 'v pralinkové krabičce',
    details: null,
    price: 160,
    amount: '15 ks',
    category: 'darkove-sady',
    subcategory: null,
    image: '../../img/sada-pralinek.jpg',
    null: null,
  },
  {
    index: '19',
    name: 'BAREVNÉ MÝDLOVÉ KYTIČKY',
    ingredients: null,
    description:
      'malinkatá mýdélka s arganovým olejem, vhodná jako drobný dárek. Balená po jednom.',
    details: null,
    price: 160,
    amount: '9 ks',
    category: 'darkove-sady',
    subcategory: null,
    image: '../../img/mydlove-kyticky.jpg',
    null: null,
  },
];

export default content;
